# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'vktime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RealmSwift', '=10.1.4'
pod 'IQKeyboardManagerSwift'
pod 'BottomPopup'
pod 'DropDown'
pod 'CalendarKit'
  # Pods for vktime

end
